In [53]:
import pandas as pd
import numpy as np

In [54]:
data = pd.read_csv(r'C:\Users\GM\Desktop\Fish_dataset.csv')

In [55]:
data

Weight  Length1  Length2  Length3   Height   Width Species
0    242.0     23.2     25.4     30.0  11.5200  4.0200   Bream
1    290.0     24.0     26.3     31.2  12.4800  4.3056   Bream
2    340.0     23.9     26.5     31.1  12.3778  4.6961   Bream
3    363.0     26.3     29.0     33.5  12.7300  4.4555   Bream
4    430.0     26.5     29.0     34.0  12.4440  5.1340   Bream
..     ...      ...      ...      ...      ...     ...     ...
86  1100.0     39.0     42.0     44.6  12.8002  6.8684   Perch
87  1000.0     39.8     43.0     45.2  11.9328  7.2772   Perch
88  1100.0     40.1     43.0     45.5  12.5125  7.4165   Perch
89  1000.0     40.2     43.5     46.0  12.6040  8.1420   Perch
90  1000.0     41.1     44.0     46.6  12.4888  7.5958   Perch

[91 rows x 7 columns]

In [56]:
data['Species'].unique()

array(['Bream', 'Perch'], dtype=object)

In [57]:
data.isnull().sum()

Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
Species    0
dtype: int64

In [58]:
colname=[]
for x in data.columns:
    if data[x].dtypes=='object':
        colname.append(x)
colname        


['Species']

In [59]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname:
    data[x]=le.fit_transform(data[x])
    
    
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print('Feature', x)
    print('mapping', le_name_mapping)

Feature Species
mapping {'Bream': 0, 'Perch': 1}


In [60]:
X = data[['Weight', 'Length1', 'Length2', 'Length3', 'Height', 'Width'] ]
Y = data['Species']

In [61]:
X.shape

(91, 6)

In [62]:
Y.shape

(91,)

In [63]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)
X = scaler.transform(X)

In [64]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [65]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='euclidean')

In [66]:
model_KNN.fit(X_train,Y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=8)

In [67]:
Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1)]


In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 6  0]
 [ 0 13]]
Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        13

    accuracy                           1.00        19
   macro avg       1.00      1.00      1.00        19
weighted avg       1.00      1.00      1.00        19

Accuracy of the model:  1.0


In [69]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()

classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[1 1 0 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1 1]
[(1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (1, 1), (1, 1), (1, 1)]


In [70]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[ 6  0]
 [ 0 13]]
Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        13

    accuracy                           1.00        19
   macro avg       1.00      1.00      1.00        19
weighted avg       1.00      1.00      1.00        19

Accuracy of the model:  1.0
